version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 4001:4001
    volumes:
      - ./src:/app/src
    depends_on: 
      - db
      
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5434
    environment: 
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
      
  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5051:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@digitrade.com
      PGADMIN_DEFAULT_PASSWORD: Aa123456